.

diff --git a/install-themes b/install-themes
--- a/install-themes
+++ b/install-themes
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e
+
 # ------------------------------------------------------------------------------
 # Print usage
 # ------------------------------------------------------------------------------
@@ -191,6 +193,8 @@ install_i3()
         i=$(sed -n "/^[ \t]*colors[ \t]*{/,/}/p" "$THEME_DIR/i3/config")
         # Replace newlines with \n
         i=$(printf "%s" "$i" | awk 'BEGIN{ORS="\\n"}{print $0}')
+        # Trim the last '\n' newline awk ads
+        i=${i%??}
         # Check if there is a bar configuration
         if grep -q "^[ \t]*bar[ \t]*{" "$HOME/.i3/config"
         then
@@ -201,7 +205,7 @@ install_i3()
                 tmp=$(sed "/^[ \t]*colors[ \t]*{/,/}/d" "$HOME/.i3/config"); printf "%s\n" "$tmp" > "$HOME/.i3/config"
             fi
             # Add the colors section to existing bar section
-            # To preserve links, we do not use sed -i, we use printf since echo interprets \\ in some shells
+            # We use awk below instead of sed since sed has some weird problems with multiline strings on busybox
             tmp=$(awk "/^[ \t]*bar[ \t]*\{[ \t]*$/{print \$0 \"\\n$i\"; next}{print}" "$HOME/.i3/config"); printf "%s\n" "$tmp" > "$HOME/.i3/config"
         fi
     else
@@ -267,8 +271,12 @@ install_xterm()
 
     # Update Xresources
     echo "-> Updating Xresources"
-    DISPLAY=:0 xrdb -merge "$HOME/.Xresources-xterm-colors"
-
+    if which xrdb > /dev/null
+    then
+        DISPLAY=:0 xrdb -merge "$HOME/.Xresources-xterm-colors"
+    else
+        echo "---> Warning: xrdb not found, Xresources will not be updated."
+    fi
     echo "Done!"
 }
 
